extends:
- stylelint-config-standard
- stylelint-rscss/config
plugins:
- stylelint-order
rules:
  indentation: 2
  order/order:
  - custom-properties
  - declarations
  - at-rules
  - rules
  order/properties-alphabetical-order: true
